// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awekncdksdamjwvaxddb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3ZWtuY2Rrc2RhbWp3dmF4ZGRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjMxMTksImV4cCI6MjA2MDg5OTExOX0.PcRiwdupZLAmB49dJuECG3JAth9bZLJYN77avdN8Le8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);